### ISSUE TITLE
Update section on packages following a change of GitHub organization for the dbt_artifacts package

### ISSUE THREAD

**Issue by benoitgoujon** [fishtown-analytics/docs.getdbt.com#1031]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/building-a-dbt-project/package-management/

### What part(s) of the page would you like to see updated?

Change the following code snippets of YAML that contain the old organization:

```yaml
packages:
  - package: tailsdotcom/dbt_artifacts
    version: 0.4.5a2
```

```yaml
packages:
  - package: tailsdotcom/dbt_artifacts
    version: [">=0.4.4", "<0.4.6"]
    install-prerelease: true
```

Replace them by:

```yaml
packages:
  - package: brooklyn-data/dbt_artifacts
    version: 0.4.5a2
```

```yaml
packages:
  - package: brooklyn-data/dbt_artifacts
    version: [">=0.4.4", "<0.4.6"]
    install-prerelease: true
```

### Additional information

[Link to the new repo](https://github.com/brooklyn-data/dbt_artifacts)
