### ISSUE TITLE
Generic tests: custom names, alt format

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#1269]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/resource-properties/tests

### What part(s) of the page would you like to see updated?

Reflect that this is possible:
```yml
models:
  - name: my_model
    columns:
      - name: id
        tests:
          - unique:
              name: my_cool_test
```

Specifically to:
- give a prettier, more recognizable name to tests with lots of arguments, which have hash-y synthetic names by default
- disambiguate multiple tests that differ _only_ in their configs (which dbt doesn't consider a difference by default, but users might) — good callout in https://github.com/dbt-labs/dbt-core/issues/4102#issuecomment-1072245658 that we'll want a clear example/guidance on this

Also, reflect that dbt now supports an alt format for defining generic tests with lots of properties:
```yml
models:
  - name: my_model
    columns:
      - name: id
        tests:
          # og format
          - accepted_values:
              name: only_allow_abc
              values: ['a', 'b', 'c']
              config:
                severity: warn
                where: 1=1
          # alt format
          - name: only_allow_abc
            test_name: accepted_values
            values: ['a', 'b', 'c']
            config:
              severity: warn
              where: 1=1
```
