### ISSUE TITLE
Selectors referencing other selectors

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#1628]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/node-selection/yaml-selectors

### What part(s) of the page would you like to see updated?

YAML selectors can now reference other selectors:
```yml
selectors:
  - name: default
    definition:
      union:
        - intersection:
          - tag: foo
          - tag: bar
  - name: inherited
    definition:
      union:
        - method: selector
          value: default
        - exclude:
          - tag: bar
```
This is useful in cases where one selector includes complex node selection logic, and another selector wants only to extend/override the same selected subset in one specific way — without having to muck around with [yaml anchors](https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/).

Obviously, if users create "cycles" of selectors that depend on each other, they'll encounter an error. This is definitely a feature targeting users of advanced node selection capabilities.

### Additional information

https://github.com/dbt-labs/dbt-core/pull/4827
