### ISSUE TITLE
Custom node coloring in docs site

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#1835]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/resource-properties/docs

### What part(s) of the page would you like to see updated?

```yml
models:
  - name: xxxx
    config:
      docs:
        node_color: "#e0115f"
```
Plus, `docs` is a real config now, and can be set for many models at once in `dbt_project.yml`, for both `show` (old) and `node_color` (new):
```yml
# dbt_project.yml

models:
  +docs:
    show: true
    node_color: "#e0115f"
```

### Additional information

- https://github.com/dbt-labs/dbt-core/pull/5397
- https://github.com/dbt-labs/dbt-docs/pull/281
