### ISSUE TITLE
Add "dynamically choose a schema" example

### ISSUE THREAD

**Issue by clrcrl** [fishtown-analytics/docs.getdbt.com#191]
```
sources:
  - name: core
    schema: "{{ 'core_production' if target.name == 'prod' else 'core_staging' }}"
    tables:
      - name: orders
```
