### ISSUE TITLE
Updates to metrics + exposures: configs, name validation

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#2052]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/building-a-dbt-project/metrics
https://docs.getdbt.com/docs/building-a-dbt-project/exposures (we should remove or update the section, "Exposures are new")

### What part(s) of the page would you like to see updated?

Metrics + exposures have validation requirements for their names, which they didn't have before. Letters, numbers, and characters only, up to a character limit. Poorly named metrics will raise an error; exposures (which have been around longer) will just raise a deprecation warning for now.

Exposures support a `label` property for human-friendly titles, just like metrics.

Metrics + exposures can now be configured, with just one built-in config: `enabled: True|False`.
```yml
# models/config.yml
metrics:
  - name: my_metric
    config:
      enabled: false

exposures:
  - name: my_exposure
    config:
      enabled: false
```
```yml
# dbt_project.yml
metrics:
  my_project:
    +enabled: false

exposures:
  my_project:
    +enabled: false
```

I think metrics are also going to support a config named `default_value_null`? (https://github.com/dbt-labs/dbt_metrics/pull/96)

### Additional information

https://github.com/dbt-labs/dbt-core/pull/5815
https://github.com/dbt-labs/dbt-core/pull/5841
https://github.com/dbt-labs/dbt-core/pull/5844
https://github.com/dbt-labs/dbt_metrics/pull/96
