### ISSUE TITLE
Upgrade to dbt_project config-version: 2 syntax

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#206]
This is going to be a _ton_ of tiny changes. E.g. one that tripped me up today:

[This](https://docs.getdbt.com/reference/resource-configs/column_types#usage)
```yml
seeds:
  jaffle_shop:
    country_codes:
      column_types:
        country_code: varchar(2)
        country_name: varchar(32)
```
needs to become
```yml
seeds:
  jaffle_shop:
    country_codes:
      +column_types:
        country_code: varchar(2)
        country_name: varchar(32)
```
