### ISSUE TITLE
Tarball URL option for `dbt deps` within `packages.yml`

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#2474]
### Context

https://github.com/dbt-labs/dbt-core/pull/4689 resolved https://github.com/dbt-labs/dbt-core/issues/4205 which added the ability to install dbt packages via tarball rather than the dbt Package Hub or git. 

### Contributions

- [X] I am a PM or subject matter expert at dbt who is responsible for this feature.

### Where does this content belong?

https://docs.getdbt.com/docs/build/packages#how-do-i-add-a-package-to-my-project

### Motivation
We should call out the [original motivation](https://github.com/dbt-labs/dbt-core/issues/4205) of this feature:
> From experience with dbt at a large org, there is no great way to distribute internal (non-public) dbt modules.

See more motivation details [here](https://github.com/dbt-labs/dbt-core/issues/4205). "[Artifactory](https://jfrog.com/artifactory/)" and "internal cloud storage bucket" could be some nice keyword terms to help show up in web searches.

### Example
YAML examples provided by @timle [here](https://github.com/dbt-labs/dbt-core/pull/4689) (subject to final spec decisions).

Currently, the new option will look something like this:
```yaml
packages:
  - tarball: https://codeload.github.com/dbt-labs/dbt-utils/tar.gz/0.9.6
    name: 'dbt_utils'
```

Where `name: 'dbt_utils'` specifies the sub-folder of `dbt_packages` that will be created for the package source code to be installed within.

---

### While we're here...

While we are updating these package docs, it wouldn't hurt to provide an example of specifying a 40-character git hash. Without having actually tried this example, I think it would look like this:
```yaml
packages:
  - git: "https://github.com/dbt-labs/dbt-utils.git"
    revision: 4e28d6da126e2940d17f697de783a717f2503188
```
