### ISSUE TITLE
Document addition of `incremental_predicates`

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#2636]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/build/incremental-models

This might want to go under the "About `incremental_strategy` section," which is really acting as our catch-all for "advanced optimizations."

### What part(s) of the page would you like to see updated?

Support for a new (optional) config: `incremental_predicates`. This config accepts any valid SQL expression. (Note: dbt will not do any validation in advance, so it's up to the user to ensure that their SQL syntax is valid.)

This is an **advanced** use of incremental models, where data volume is large enough to justify additional investments in performance. It's a real case of "trust the user," where some of the abstraction that dbt offers over vendor-specific `merge` statements is stripped away.

For instance, this is a pattern we might expect to see on Snowflake:
```yml
models:
  - name: my_incremental_model
    config:
      materialized: incremental
      unique_key: id
      cluster_by: ['session_start']  # this will affect how the data is stored on disk, and indexed to limit scans
      incremental_strategy: merge
      # limit scan of the existing table to the last 7 days of data
      incremental_predicates: "DBT_INTERNAL_DEST.session_start > datediff(day, -7, current_date)"
```

This will template a `merge` statement like:
```sql
merge into <existing_table> DBT_INTERNAL_DEST
    from <temp_table_with_new_records> DBT_INTERNAL_SOURCE
    on
        -- unique key
        DBT_INTERNAL_DEST.id = DBT_INTERNAL_SOURCE.id
        and
        -- custom predicate: limits data scan in the "old" data / existing table
        DBT_INTERNAL_DEST.session_start > datediff(day, -7, current_date)
    when matched then update ...
    when not matched then insert ...
```

The user will still want to limit data scan of _upstream_ tables, like always, within the body of their incremental model SQL, to limit the amount of "new" data being processed / transformed:
```sql
with large_source_table as (

    select * from {{ ref('large_source_table') }}
    {% if is_incremental() %}
        where session_start > dateadd(day, -3, current_date)
    {% endif %}

),

...
```

Notes:
- Users do need to explicitly alias any columns with either `DBT_INTERNAL_DEST` ("old" data) or `DBT_INTERNAL_SOURCE` ("new" data)
- There's a decent amount of conceptual overlap with the `insert_overwrite` incremental strategy. This whole section of the docs probably needs some more love, &/or to link to a revised version of https://discourse.getdbt.com/t/bigquery-dbt-incremental-changes/982 (which is now nearly 3 years old).

### Additional information

Relevant merged PRs:
- https://github.com/dbt-labs/dbt-core/pull/5702
- https://github.com/dbt-labs/dbt-bigquery/pull/284
- https://github.com/dbt-labs/dbt-spark/pull/436
- https://github.com/databricks/dbt-databricks/pull/161/
- https://github.com/dbt-labs/dbt-snowflake/pull/310

For much much more context on the performance benefits of "bounding" the scan, e.g. to take advantage of a cluster key on Snowflake:
- https://github.com/dbt-labs/dbt-core/issues/3293
- https://github.com/dbt-labs/dbt-snowflake/issues/231
