### ISSUE TITLE
Exposures can depend on metrics

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#2638]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/build/exposures
https://docs.getdbt.com/reference/exposure-properties

### What part(s) of the page would you like to see updated?

```yml
exposures:
  - name: my_exposure
    depends_on:
      - ref('some_model')
      - ref('some_seed')
      - source('name', 'table')
      - metric('some_metric')
```

---

While we're here: Should an `exposure` ever depend on a `source` directly, without at least a staging model in between? Our recommendation should be: probably not! / likely never!

Still, it should be _possible_.

To quote @joellabes from Slack ~a month ago:
> Agree that it is an antipattern, but also want to note that part of the docs' job is also to say what is possible so would advise against removing that `source` example.
> Add a note in the docs to say "you can but you shouldn't" would be useful though!

### Additional information

https://github.com/dbt-labs/dbt-core/pull/6342
