### ISSUE TITLE
Demonstrate using `env_var` for secrets on the `profiles.yml` page

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#2816]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

This appears to be the main page for profiles.yml:
- https://docs.getdbt.com/docs/get-started/connection-profiles

The topic that I consider is the most important for profiles.yml is handling credential secrets. This is only covered on this page:
- https://docs.getdbt.com/reference/dbt-jinja-functions/env_var

### What part(s) of the page would you like to see updated?

I think the following example should be included on _both_ pages!

Maybe we can create a **re-usable snippet** for it?

```yaml
profile:
  target: prod
  outputs:
    prod:
      type: postgres
      host: 127.0.0.1
      # IMPORTANT: Make sure to quote the entire Jinja string here
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      ....
```

In my view, the most useful place to include it would be right after here:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/44704949/216652627-8df1afd9-04b1-4235-903e-43bce56bf04b.png">

If I had my druthers, we'd actually completely replace the code in the screenshot above with the `env_var()` version of the example.

The main reason why _not_ to replace the hard-coded example that uses `password: <password>` with `password: "{{ env_var('DBT_PASSWORD') }}"` is that the latter is a little higher barrier for many users -- it requires configuring environment variables, and method to accomplish that will vary depending on the operating and/or command-line shell of the user.

However, we could make the counter argument that setting/unsetting environment variables is a broadly useful skill that we should encourage and educate about.

Regardless, I think we should make the `env_var()` version of `profiles.yml` _impossible_ to miss in our docs.
