### ISSUE TITLE
Keeping the original filename and table name when versioning for first time

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#3203]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/collaborate/govern/model-versions

### What part(s) of the page would you like to see updated?

[These](https://github.com/dbt-labs/docs.getdbt.com/pull/3195/files#diff-017bcb1f6a6ac50cbc818ffd9b893335887dd422783f1a2bf125e15bee36c895R95-R101) changes need to be reviewed for completeness and correctness.

The instigating issue was this this didn't work for me:
```yaml
  - v: 1
    config:
      alias: dim_customers # keep old relation location
```

This is what worked for me to keep both the filename and the table name the same as when it was un-versioned:
`models/_models.yml`
```yaml
models:
  - name: dim_customers
    versions:
      - v: 1
        defined_in: dim_customers  # keep original file name
```

`models/dim_customers.sql`
```yaml
{{ config(alias="dim_customers") }}

...
```

After my changes in #3195, this is not accurate 😢 :
```yaml
defined_in: dim_customers # keep original relation name
```

It should be something like this instead:
```yaml
defined_in: dim_customers # keep original file name
```
