### ISSUE TITLE
dbt-bigquery `submission_method` config in `profiles.yml`

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#3383]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

There is already some documentation for `submission_method` [here](https://docs.getdbt.com/docs/build/python-models#specific-data-platforms) (under BigQuery > Submission methods).

But I didn't see any actual examples of `profiles.yml` with the relevant option(s), which I'm guessing would go here:
https://docs.getdbt.com/reference/warehouse-setups/bigquery-setup

Either immediately above or below (or merged with) this section:
https://docs.getdbt.com/reference/warehouse-setups/bigquery-setup#running-python-models-on-dataproc

### What part(s) of the page would you like to see updated?

Here's an example that has `submission_method`:

`profiles.yml`
```yaml
myproject:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT') }}"
      dataset: tmp
      threads: 4
      gcs_bucket: "my-bucket"
      dataproc_region: "europe-west1"
      submission_method: serverless
      dataproc_batch:
        batch_id: my_custom_batch_id
        environment_config:
          execution_config:
            service_account: "dbt@{{ env_var('GCP_PROJECT') }}.iam.gserviceaccount.com"
            subnetwork_uri: "dataproc"
        labels:
          project: "my-project"
          role: "dev"
        runtime_config:
          properties:
            spark.executor.instances: 3
            spark.driver.memory: "1g"
```
