### ISSUE TITLE
Add diagram(s) to explain different indirect selection modes

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#3403]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/node-selection/test-selection-examples#indirect-selection

### What part(s) of the page would you like to see updated?

We should add helpful diagram(s) as mentioned in https://github.com/dbt-labs/dbt-core/issues/6365#issuecomment-1348343464

> We'll want to clearly document it [here](https://docs.getdbt.com/reference/node-selection/test-selection-examples#indirect-selection); including a diagram like the one above would be particularly helpful, not just for the new buildable mode, but to illustrate the existing ones as well.

<img width="450" alt="image" src="https://user-images.githubusercontent.com/44704949/206818219-24bc93ea-8e54-43bf-814f-d8f6b4fc4899.png">

### Additional information

Here are the diagrams I've found most helpful: https://github.com/dbt-labs/dbt-core/issues/9746#issuecomment-1989027389

**Comment by dbeatty10** [comment]
Content below was copy-pasted from https://github.com/dbt-labs/dbt-core/issues/9746#issuecomment-1989027389

### Visual examples of indirect selection

A DAG like the following will execute **all** model and test nodes when you run `dbt build`:

<img width="300" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/c6809e99-235e-4a61-a55d-aa9df74f1095">

See below for visual examples of how each of the four modes for [indirect selection](https://docs.getdbt.com/reference/node-selection/test-selection-examples?indirect-selection-mode=buildable#indirect-selection) will affect which nodes are executed when only `model_b` is selected:
1. eager (default)
1. buildable
1. cautious
1. empty

<details>
<summary>

### Project files
</summary>

`models/model_a.sql`

```sql
select 1 as id
```

`models/model_b.sql`

```sql
-- {{ ref("model_a") }}
select 1 as id
```

`models/model_c.sql`

```sql
-- {{ ref("model_b") }}
select 1 as id
```

`models/_models.yml`

```yaml
models:
  - name: model_a
    columns:
      - name: id
        tests:
          - not_null:
              name: test_a
          - relationships:
              name: test_ab
              to: ref("model_b")
              field: id
  - name: model_b
    columns:
      - name: id
        tests:
          - not_null:
              name: test_b
  - name: model_c
    columns:
      - name: id
        tests:
          - relationships:
              name: test_bc
              to: ref("model_b")
              field: id
```

</details>

### Eager (default)

```shell
dbt build -s model_b --indirect-selection eager
```

<img width="350" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/4356ccaa-1877-41cb-ac60-71ab0686a109">

### Buildable

```shell
dbt build -s model_b --indirect-selection buildable
```

<img width="350" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/1a5ffe75-b90d-46a5-8735-01d43b552d16">

### Cautious

```shell
dbt build -s model_b --indirect-selection cautious
```

<img width="350" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/354ce2d7-fdba-4db5-bbed-bfc2af08eddb">

### Empty

```shell
dbt build -s model_b --indirect-selection empty
```

<img width="350" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/f65f12b4-cd69-4973-a640-a02006bd45ca">
