### ISSUE TITLE
Add examples of all types of constraints

### ISSUE THREAD

**Issue by MichelleArk** [fishtown-analytics/docs.getdbt.com#3443]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/resource-properties/constraints

### What part(s) of the page would you like to see updated?

the models/schema.yml file under https://docs.getdbt.com/reference/resource-properties/constraints#defining-constraints

We already have examples of `primary_key`, `check`, and `not_null` types across model/column level constraints!

Let's add an example usage of a `foreign_key`, `unique` and potentially `custom` types as well. For example, 
```yml
columns:
     - name: <first_column>
       data_type: <data_type>

       # column-level constraints
       constraints:
        - type: not_null
        - type: unique
        - type: foreign_key
          expression: <other_model_schema>.<other_model_name> (<other_model_column>)
       - type: ...
```

I believe we're also missing the `unique` type from the list of supported types.
