### ISSUE TITLE
Model access: `enforce_access` for packages

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#3573]
**Note: This is still in design/implementation**

_Copying from https://github.com/dbt-labs/dbt-core/issues/7713#issuecomment-1584795533:_

IMO differentiation between `public` & `private` access is an important part of the `dbt-core` language construct for model access. It should be possible to enforce this, even if you're just adopting a "mesh" paradigm via packages. It should be opt-in (for now) to avoid breaking status quo, but we might want to make this "on" by default in a future version of dbt (perhaps v2).

Let's call it `enforce_access`. When set to `True`, we should raise an error during ref resolution if a model with `access: protected` is being referenced across projects.

```yml
# packages.yml
packages:
  - git: https://my-org/upstream-project
    enforce_access: True  # default is False
```
