### ISSUE TITLE
Add docs for configs for semantic models

### ISSUE THREAD

**Issue by FishtownBuildBot** [fishtown-analytics/docs.getdbt.com#3997]
Related PR: https://github.com/dbt-labs/dbt-core/pull/8502

### Page to update
https://docs.getdbt.com/docs/build/semantic-models#semantic-models-components

### What to update
Semantic models now support configs in the schema file or at the project level

models/semantic.yml
```yml
semantic_models:
  - name: orders
    config:
      enabled: true | false
      group: some_group
      meta: {"some_key": "some_value"}
```

dbt_project.yml
```yml
semantic-models:
  my_project_name:
    +enabled: true | false
    +group: some_group
    +meta: {"some_key": "some_value"}
```
