### ISSUE TITLE
Allow setting `access` as a config

### ISSUE THREAD

**Issue by FishtownBuildBot** [fishtown-analytics/docs.getdbt.com#4075]
Read this issue for context & motivation:
- https://github.com/dbt-labs/dbt-core/issues/7619

### Where to change?

https://docs.getdbt.com/docs/collaborate/govern/model-access
https://docs.getdbt.com/reference/resource-properties/access - move from "General properties" to "General configs"

### What's the change?

Starting in dbt-core v1.7, it will be possible to set `access` as a "config", instead of just as a "property":
```yaml
# dbt_project.yml
models:
  my_project_name:
    subfolder_name:
      +group: <my_group>
      +access: private  # sets default for all models in this subfolder
```

```yaml
models:
  - name: my_public_model
    access: public # previous, still supported
    config:
      access: public # newly supported
    
    # you just cannot set it in *both* places
```

```
-- models/my_public_model.sql

{{ config(access = "public") }}

select ...
```
