### ISSUE TITLE
Supported configs (`meta`, `enabled`, `group`) for semantic models

### ISSUE THREAD

**Issue by FishtownBuildBot** [fishtown-analytics/docs.getdbt.com#4180]
At a minimum, update body to include a link to the page on docs.getdbt.com requiring updates and what part(s) of the page you would like to see updated.

Relevant PRs: https://github.com/dbt-labs/dbt-core/pull/8754, https://github.com/dbt-labs/dbt-core/pull/8766

Pages to update:
- https://docs.getdbt.com/reference/resource-configs/meta
- https://docs.getdbt.com/reference/resource-configs/enabled
- https://docs.getdbt.com/reference/resource-configs/group
- https://docs.getdbt.com/reference/resource-properties/config
- https://docs.getdbt.com/docs/build/semantic-models

New things for `semantic_models`:
- `meta` can now be nested under a `config` key (config added in [#8754](https://github.com/dbt-labs/dbt-core/pull/8754))
- `enabled` can now be nested under a `config` key (config added in [#8502](https://github.com/dbt-labs/dbt-core/pull/8502))
- `group` can now be nested under a `config` key (config added in [#8502](https://github.com/dbt-labs/dbt-core/pull/8502))

### Examples

[This](https://docs.getdbt.com/reference/resource-configs/meta) page should add a "Semantic models" tab that includes an example like the following:

`models/semantic_models.yml`
```yaml
semantic_models:
  - name: semantic_people
    model: ref('people')
    config:
      meta: {<dictionary>}
```

And [this](https://docs.getdbt.com/reference/resource-configs/enabled) page should have an example like this:

`models/semantic_models.yml`
```yaml
semantic_models:
  - name: semantic_people
    model: ref('people')
    config:
      enabled: false
```

And [this](https://docs.getdbt.com/reference/resource-configs/group) page include examples like this:

`schema.yml`
```yaml
semantic_models:
  - name: model_name
    config:
      group: finance
```

`dbt_project.yml`
```yaml
semantic-models:
  [<resource-path>](resource-path):
    +group: finance
```
