### ISSUE TITLE
Type aliasing for model contract column `data_type`

### ISSUE THREAD

**Issue by FishtownBuildBot** [fishtown-analytics/docs.getdbt.com#4241]
dbt will use its built-in type aliasing for model contracts. This means you can specify `string` in your contract, and on Postgres/Redshift dbt will convert it to `text`. If dbt doesn't recognize the data type name among its known aliases, it will simply pass it through.

As of v1.7, this is on by default. Users can opt out by setting:
```yml
models:
  - name: my_model
    config:
      contract:
        enforced: true
        alias_types: false  # true by default
```
