### ISSUE TITLE
Optional exports within saved queries

### ISSUE THREAD

**Issue by FishtownBuildBot** [fishtown-analytics/docs.getdbt.com#4381]
At a minimum, update body to include a link to the page on docs.getdbt.com requiring updates and what part(s) of the page you would like to see updated.

### Issue / PR

https://github.com/dbt-labs/dbt-core/issues/8892 / https://github.com/dbt-labs/dbt-core/pull/8950

### Example

Example from [here](https://github.com/dbt-labs/dbt-core/blob/e24f9b3da722328e24ee10a06fa2e8d2ca73b3e6/tests/functional/saved_queries/fixtures.py#L8-L25):
```yaml
saved_queries:
  - name: test_saved_query
    description: "{{ doc('saved_query_description') }}"
    label: Test Saved Query
    query_params:
        metrics:
            - simple_metric
        group_by:
            - "Dimension('user__ds')"
        where:
            - "{{ Dimension('user__ds', 'DAY') }} <= now()"
            - "{{ Dimension('user__ds', 'DAY') }} >= '2023-01-01'"
    exports:
        - name: my_export
          config:
            alias: my_export_alias
            export_as: table
            schema: my_export_schema_name
```
