### ISSUE TITLE
Check code examples for the `docs` config

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#4449]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

- https://docs.getdbt.com/reference/resource-configs/docs
- https://docs.getdbt.com/reference/macro-properties

### What part(s) of the page would you like to see updated?

https://github.com/dbt-labs/docs.getdbt.com/commit/1c959fd966c5d3e81c987c756145c55cbe099a4b added a couple inline "to-do" comments like this:

https://github.com/dbt-labs/docs.getdbt.com/blob/0cb4856b498a8ce5233774142ecebbeb20883188/website/docs/reference/resource-configs/docs.md?plain=1#L97

So I'd suggest checking if each of these examples work correctly or not. If a code example works, then remove the `to-do` comment. If it doesn't, then update the docs as-needed.

### Example 1 - **Macros** tab

`macros/schema.yml`

```yml
version: 2
macros:
  - name: macro_name
    docs:
      show: true | false
```

### Example 2 - **Macros properties** page

```yml
version: 2

macros:
  - name: <macro name>
    [description](description): <markdown_string>
    [docs](docs):
      show: true | false
    arguments:
      - name: <arg name>
        type: <arg type>
        [description](description): <markdown_string>
      - ...
  - ...
```
