### ISSUE TITLE
Update docs for `node_color`

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#4492]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/resource-configs/docs

### What part(s) of the page would you like to see updated?

Two things:
1. Expand code examples across all applicable node types
2. (Option) Consider more explicit language of which node types support `node_color` (or not)

### More explanation

Only the model node type includes `node_color` within its general code [example](https://docs.getdbt.com/reference/resource-configs/docs):

<img width="500" alt="image" src="https://github.com/dbt-labs/docs.getdbt.com/assets/44704949/76ed2934-6865-44cd-bd2a-780eb6f3126f">

And [elsewhere](https://docs.getdbt.com/reference/resource-configs/docs#definition), it only says "some node types" rather than being explicit about which support "node_color" and which don't:

<img width="500" alt="image" src="https://github.com/dbt-labs/docs.getdbt.com/assets/44704949/a70bcd97-d3e9-4c5e-ba26-6b984b50a67f">

### Additional information

`node_color` was added within https://github.com/dbt-labs/dbt-core/pull/5397

See https://github.com/dbt-labs/dbt-core/issues/8061#issuecomment-1863292897 for an adjacent issue.

**Comment by mirnawong1** [comment]
hey @dbeatty10 , does this mean that only models support node_color? everywhere I've looked, it seems like the only node type that supports node_color is models?

**Comment by mirnawong1** [comment]
hey @dbeatty10 , i've created this pr here https://github.com/dbt-labs/docs.getdbt.com/pull/4493/files to address this but i'll add more to it once you have a chance to review this issue.

**Comment by mirnawong1** [comment]
following up

**Comment by dbeatty10** [comment]
@mirnawong1 I don't know either way if there are node types besides models that support the `node_color`. One way to determine one way or another is to try it with a bunch of node types and see if it affects the display of the auto-generated documentation site or not.

i.e., try it with `seeds`, `sources`, `snapshots`, and `analyses` and see what happens.

**Comment by dbeatty10** [comment]
> i.e., try it with `seeds`, `sources`, `snapshots`, and `analyses` and see what happens.

I just tried this out, and the ones in `purple` are the ones that worked:

<img width="600" alt="image" src="https://github.com/dbt-labs/docs.getdbt.com/assets/44704949/454ab102-67ab-463e-91a1-9299f3a66673">

So these ones worked:
- model
- seed
- analysis
- snapshot

But these did not:
- source
- semantic model
- metric
- exposure

<details>
<summary>

### Reprex
</summary>

`models/_properties.yml`

```yaml
version: 2


models:
  - name: my_model
    docs:
      show: true
      node_color: "purple"
    columns:
      - name: id
        tests:
          - not_null

sources:
  - name: my_source
    tables:
      - name: my_source_table

seeds:
  - name: my_seed
    docs:
      show: true
      node_color: "purple"

snapshots:
  - name: my_snapshot
    docs:
      show: true
      node_color: "purple"

analyses:
  - name: my_analysis
    docs:
      show: true
      node_color: "purple"

exposures:
  - name: my_exposure
    label: my_exposure
    type: dashboard
    maturity: high
    url: https://bi.tool/dashboards/1

    depends_on:
      - ref('my_model')
      - ref('my_seed')
      - ref('my_snapshot')

    owner:
      name: Callum McData
      email: data@jaffleshop.com

metrics:
  - name: my_metric
    label: my_metric
    type: derived
    type_params:
      expr: revenue - cost

semantic_models:
  - name: my_semantic_model
    model: ref('metricflow_time_spine')

# See: https://github.com/dbt-labs/dbt-docs/issues/486

# saved_queries:
#   - name: p0_booking
#     description: Booking-related metrics that are of the highest priority.
#     query_params:
#       metrics:
#         - my_metric
```

```shell
cat models/my_model.sql seeds/my_seed.csv snapshots/my_snapshot.sql analyses/my_analysis.sql | pbcopy
```

`models/my_model.sql`

```sql
-- {{ source("my_source", "my_source_table") }}
select 1 as id
```

`seeds/my_seed.csv`

```csv
id
1
```

`snapshots/my_snapshot.sql`

```sql
{% snapshot my_snapshot %}

{{
    config(
      target_database=target.database,
      target_schema=target.schema,
      unique_key='id',
      strategy='check',
      check_cols='all',
    )
}}

select 1 as id

{% endsnapshot %}
```

`analyses/my_analysis.sql`

```sql
select 1 as id from {{ source("my_source", "my_source_table") }}
```

`models/metricflow_time_spine.sql`

```sql
-- https://docs.getdbt.com/docs/build/metricflow-time-spine

{{ config(materialized='table') }}

with days as (

    {{
        dbt.date_spine(
            'day',
            "to_date('2000-01-01', 'YYYY-MM-DD')",
            "to_date('2000-01-05', 'YYYY-MM-DD')"
        )
    }}

),

final as (
    select cast(date_day as date) as date_day
    from days
)

select * from final
```

`models/my_test_model.sql`

```sql
select 1 as id
```

`models/_unit.yml`

```yml
unit_tests:

  - name: my_unit_test
    given: []
    model: my_test_model
    expect:
      rows:
        - {id: 1}
```

</details>
