### ISSUE TITLE
document new project flag source_freshness_run_project_hooks

### ISSUE THREAD

**Issue by FishtownBuildBot** [fishtown-analytics/docs.getdbt.com#4787]
In https://github.com/dbt-labs/dbt-core/pull/9366, we introduced a new project flag - `source_freshness_run_project_hooks: true | false`. This flag is _only_ configurable in the dbt_project.yml file, and has no corresponding CLI option or environment variable.

When enabled, project hooks (on-run-start and on-run-end) run as part of the source freshness command. By default, the flag is disabled, meaning that project hooks are not run as part of the source freshness command.

Syntax example

```yml
#dbt_project.yml
flags: 
  ...
  source_freshness_run_project_hooks: true | false
  ...
```
