### ISSUE TITLE
`<resource_type>/properties.yml` examples for the `enabled` config

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#4859]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/resource-configs/enabled

### What part(s) of the page would you like to see updated?

Under the tab for each resource type, determine if `enabled` can be set underneath a `config` key within `<resource_type>/properties.yml` or not.

If so, then add a `<resource_type>/properties.yml` example for that resource type.

### One example

For example, this works for tests, and **presumably** you can similar set configs for models, seeds, etc too:

```yaml
models:
  - name: orders
    columns:
      - name: order_id
        tests:
          - unique:
              enabled: false
```

We'd just need to double-check each of the other resource types as well.

### Additional information

This was raised in [this](https://www.notion.so/WIP-how-do-I-know-the-primary-key-of-my-model-dbt-audit-f7a348e630b94c2693b85141cd708847?d=3679066aeaf24fcfb143d0fbb330bfb1&pvs=4#96e71907b5d84c24968adfe8dba4990d) internal conversation.
