### ISSUE TITLE
Docs Changes Needed from dbt-core PR #9580

### ISSUE THREAD

**Issue by FishtownBuildBot** [fishtown-analytics/docs.getdbt.com#4945]
`meta` should now be nested under the `config` key for `Metrics`.

```
metrics:
  - name: number_of_people
    label: "Number of people"
    description: Total count of people
    type: simple
    type_params:
      measure: people
    config:
      meta:
         my_meta_config: 'config
```

However we still support the deprecated method os listing it as a toplevel key
```
metrics:
  - name: number_of_people
    label: "Number of people"
    description: Total count of people
    type: simple
    type_params:
      measure: people
    meta:
        my_meta_direct: 'direct'
```

More details in https://github.com/dbt-labs/dbt-core/issues/9441
