### ISSUE TITLE
Docs Changes Needed from dbt-core PR #9588

### ISSUE THREAD

**Issue by FishtownBuildBot** [fishtown-analytics/docs.getdbt.com#4946]
The `SavedQuery` config now accepts  `cache` with `enabled: True` or `enabled: False`.  If not defined, it defaults to a value of false.

```
saved_queries:
  - name: test_saved_query
    description: "{{ doc('saved_query_description') }}"
    label: Test Saved Query
    config:
      cache:
        enabled: True
    query_params:
        metrics:
            - simple_metric
        group_by:
            - "Dimension('user__ds')"
        where:
            - "{{ Dimension('user__ds', 'DAY') }} <= now()"
            - "{{ Dimension('user__ds', 'DAY') }} >= '2023-01-01'"
    exports:
        - name: my_export
          config:
            alias: my_export_alias
            export_as: table
            schema: my_export_schema_name
```

More details in https://github.com/dbt-labs/dbt-core/issues/9540 and pending changes in SL for https://github.com/dbt-labs/dbt-semantic-interfaces/issues/252
