### ISSUE TITLE
[Core] Allow generic tests to accept arbitrary configs

### ISSUE THREAD

**Issue by McKnight-42** [fishtown-analytics/docs.getdbt.com#5548]
### Link to the page(s) on docs.getdbt.com requiring updates

tbd

### Tell us more about this update

We will want to update our `tests` configs to be able to take whatever config the user wants to set as we do for eg. `models`
An example of an appropriate config that would benefit from this would be `snowflake_warehouse` so that users can define the virtual warehouse they use for tests in Snowflake.

### Reviewers/Stakeholders/SMEs

adapters team (Matthew McKnight)

### Related GitHub issues

- https://github.com/dbt-labs/dbt-core/issues/10197
- https://github.com/dbt-labs/dbt-core/issues/10198
- https://github.com/dbt-labs/dbt-snowflake/issues/1059 - should just be adding tests for the above in adapter repo.
- https://github.com/dbt-labs/dbt-core/issues/10484 - bug that needs to be fix prior to shipping this feature
- https://github.com/dbt-labs/dbt-snowflake/pull/1172

**Comment by McKnight-42** [comment]
I believe around here would be the place to make the change https://docs.getdbt.com/reference/data-test-configs#data-test-specific-configurations as this is where we define the `Data-test` specific and `Generic` configs for tests.

possibly want to add an example here https://docs.getdbt.com/reference/data-test-configs#examples

showing we can add any config.
```
models:
  - name: my_model
    columns:
      - name: id
        tests:
          - unique:
          - config:
             custom_config: custom_value
```
