### ISSUE TITLE
[Core] How to add a description for custom generic tests

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#5631]
### Link to the page(s) on docs.getdbt.com requiring updates

https://docs.getdbt.com/best-practices/writing-custom-generic-tests

### Tell us more about this update

There are two types of data tests, and users can create custom tests in both types:
- generic
- singular

When creating a custom generic test, many users want to add a description that shows up in the [generated docs site](https://docs.getdbt.com/docs/collaborate/documentation).

One user described how to accomplish this goal: https://github.com/dbt-labs/dbt-core/issues/2578#issuecomment-1868473901

e.g., do something like this:

`macros/_generic_data_tests.yml` ~or `tests/generic/_generic_data_tests.yml`~ (EDIT: the 2nd one didn't work for me)

```yaml
macros:
  - name: test_not_empty_string
    description: Complementary test to default `not_null` test as it checks that there is not an empty string. It only accepts columns of type string. It is deprecated as this functionality has been included in the custom implementation of `not_null`
    arguments:
      - name: model
        type: string
        description: Model Name
      - name: column_name
        type: string
        description: Column name that should not be an empty string
```

Note: it doesn't strictly need to be named `_generic_data_tests.yml`; it could be something else like `properties.yml`.

### Reviewers/Stakeholders/SMEs

.

### Related GitHub issues

- https://github.com/dbt-labs/dbt-core/issues/2578
- https://github.com/dbt-labs/dbt-core/issues/10272

**Comment by dbeatty10** [comment]
@mirnawong1 I'm re-opening this because #6940 doesn't match the intent of this issue.

https://github.com/dbt-labs/docs.getdbt.com/issues/6193 describes (3) totally different ways to add a description to data tests:

1. Definitions of generic data tests
2. Instances of generic data tests
3. Instances of singular data tests

#6940 provides good examples of (2) 💡
But this issue is asking for an example of (1) 👈 

What's the difference between a _definition_ and an _instance_?
- By "definition", I mean the Jinja macro that provides the code/logic for the data test (independent of that data test actually being used anywhere).
- By "instance", I mean the YAML where the data test is actually added to a model/seed/etc.

So for (2), we'll want our docs to include an example of adding a description to the macro associated with the data test like this:

```yaml
macros:
  - name: test_not_empty_string
    description: Complementary test to default `not_null` test as it checks that there is not an empty string. It only accepts columns of type string. It is deprecated as this functionality has been included in the custom implementation of `not_null`
    arguments:
      - name: model
        type: string
        description: Model Name
      - name: column_name
        type: string
        description: Column name that should not be an empty string
```

👉 Note that the `description` here is under the `macros:` key.
