### ISSUE TITLE
Invalid yaml in Aliasing - test tab

### ISSUE THREAD

**Issue by acarter24** [fishtown-analytics/docs.getdbt.com#5802]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/resource-configs/alias

Under 'test' tab, the yaml in the box is not valid

### What part(s) of the page would you like to see updated?

```
models:
  - name: orders
    columns:
      - name: order_id
        tests:
          - unique
            alias: unique_order_id_test
```
