### ISSUE TITLE
Time spines without YAML configuration are in the process of deprecation. Please add YAML configuration for your 'metricflow_time_spine' model

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#5908]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/build/metricflow-time-spine

### What part(s) of the page would you like to see updated?

I'm getting this warning:

```
16:25:18 Time spines without YAML configuration are in the process of deprecation. Please add YAML configuration for your 'metricflow_time_spine' model. See documentation to configure: https://docs.getdbt.com/docs/build/metricflow-time-spine
```

<img width="881" alt="image" src="https://github.com/user-attachments/assets/16d4509b-ab9e-4ff4-aa53-ea8aaaf7cf9f">

But when I click the [link](https://docs.getdbt.com/docs/build/metricflow-time-spine), it doesn't include any information about configuring the YAML.

We should add examples of how to configure the time spines in YAML.

### Additional information

Other folks have run into this warning, see https://github.com/dbt-labs/dbt-core/pull/10483#issuecomment-2270078723 for an example.

When https://github.com/dbt-labs/docs.getdbt.com/issues/5857 is resolved, it should resolve this issue as well.

I was able to suppress this warning by adding the following to `models/_models.yml`:

```yaml
models:
  - name: metricflow_time_spine
    time_spine:
      standard_granularity_column: date_day
    columns:
      - name: date_day
        granularity: day
```
