### ISSUE TITLE
Update example configuration of dbt_cloud.yml file

### ISSUE THREAD

**Issue by glsdown** [fishtown-analytics/docs.getdbt.com#5970]
### Contributions

- [x] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/cloud/configure-cloud-cli

### What part(s) of the page would you like to see updated?

The example config appears to be out of date:

```yml
version: "1"
context:
    active-project: "<project id from the list below>"
    active-host: "<active host from the list>"
    defer-env-id: "<optional defer environment id>"
projects:
- project-id: "<project-id>"
    account-host: "<account-host>"
    api-key: "<user-api-key>"

- project-id: "<project-id>"
    account-host: "<account-host>"
    api-key: "<user-api-key>"
```

When used, it gives the warning:

```
WARNING: User API Keys are being deprecated on September 18th, 2024 in favor of Personal Access Tokens - to upgrade, download your dbt_cloud.yml file again.
```

I believe the new structure should be:

```yml
version: "1"
context:
  active-project: "<project id from the list below>"
  active-host: "<active host from the list>"
  defer-env-id: "<optional defer environment id>"
projects:
  - project-name: "<project-name>"
    project-id: "<project-id>"
    account-name: "<account-name>"
    account-id: "<account-id>"
    account-host: "<account-host>" # e.g. "cloud.getdbt.com"
    token-name: "<pat-or-service-token-name>"
    token-value: "<pat-or-service-token-value>"

  - project-name: "<project-name>"
    project-id: "<project-id>"
    account-name: "<account-name>"
    account-id: "<account-id>"
    account-host: "<account-host>" # e.g. "cloud.getdbt.com"
    token-name: "<pat-or-service-token-name>"
    token-value: "<pat-or-service-token-value>"
```
