### ISSUE TITLE
[Core] Foreign key constraints support `to` (with `ref`) + `to_columns`

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#5983]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/resource-properties/constraints

### What part(s) of the page would you like to see updated?

_Copied from https://github.com/dbt-labs/dbt-core/pull/10414#issuecomment-2243915257_

Model-level constraint example syntax: 
```yaml
models:
  - name: my_model
    constraints:
      - type: foreign_key
        columns: [id]
        to: ref('my_model_to') | source('source', 'source_table')
        to_columns: [id]
    columns:
      - name: id
        data_type: integer
```

Column-level example syntax:
```yaml
models:
  - name: my_model
    columns:
      - name: id
        data_type: integer
        constraints:
        - type: foreign_key
          to: ref('my_model_to') | source('source', 'source_table')
          to_columns: [id]
```

### Additional information

This is already available in dbt Cloud Versionless

This will be available in dbt Core (OSS) v1.9
