### ISSUE TITLE
Review code example for `saved-queries` in `dbt_project.yml`

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#6066]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/dbt_project.yml#naming-convention

### What part(s) of the page would you like to see updated?

I didn't test it out one way or the other, but [this](https://docs.getdbt.com/reference/dbt_project.yml#naming-convention) code example doesn't look right to me:

<img width="600" alt="image" src="https://github.com/user-attachments/assets/eae566d0-9fe0-4751-8cb9-4c97597ffb11">

Rather, I'd expect it to look like [this](https://docs.getdbt.com/reference/resource-configs/enabled) example:

<img width="600" alt="image" src="https://github.com/user-attachments/assets/b4a9ecc0-17f1-49c8-9584-f2c9e2b4cc55">

So something more like:

```yaml
saved-queries:  # Use dashes for resource types in the dbt_project.yml file.
  my_project_name:
    +cache:
      enabled: true
```
