### ISSUE TITLE
Multiple tag selection / exclusion

### ISSUE THREAD

**Issue by reubster** [fishtown-analytics/docs.getdbt.com#610]
I discovered by experiment that I can exclude multiple tags by for example; 

```
    definition:
      union:
        - method: fqn
          value: "*"
        - exclude:
          - method: tag
            value: exclude_A
          - method: tag
          - value: exclude_B
```

I'm guessing there might be other forms..? Just needs a few examples of various kinds of multiple criteria selection.
