### ISSUE TITLE
Explain specifying project dependencies independent of package dependencies

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#6176]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/collaborate/govern/project-dependencies

### What part(s) of the page would you like to see updated?

As described [here](https://docs.getdbt.com/docs/collaborate/govern/project-dependencies), dbt has two types of dependencies:
1. Package dependencies
1. Project dependencies

Here's what each of them look like:

```yaml
# Packages

packages:
  - package: dbt-labs/dbt_utils
    version: 1.1.1
```

```yaml
# Projects

projects:
  - name: jaffle_finance  # case sensitive and matches the 'name' in the 'dbt_project.yml'
```

👉 The problem that would be great to solve:
- There is a stand-alone section describing ["How do I specify a package?"](https://docs-getdbt-com-git-simplify-recommendations-dbt-labs.vercel.app/docs/build/packages#how-do-i-specify-a-package), but there **does not** exist a stand-alone section describing "How do I specify a project dependency?".

I think we should do the following:
1. Add that stand-alone section somewhere (probably within this page)
1. Link **"Package" dependencies** [here](https://docs.getdbt.com/docs/collaborate/govern/project-dependencies#use-cases) to that section
1. Link **"Project" dependencies** [here](https://docs.getdbt.com/docs/collaborate/govern/project-dependencies#use-cases) to [this](https://docs-getdbt-com-git-simplify-recommendations-dbt-labs.vercel.app/docs/build/packages#how-do-i-specify-a-package) section

That way, the links show exactly how to specify each type of dependency in a stand-alone fashion. Then a user can see how to specify them either in separate files (`packages.yml` and `dependencies.yml`) or the same file (`dependencies.yml`).
