### ISSUE TITLE
Adding a description for singular data tests and custom generic data tests

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#6193]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

Not sure exactly which pages -- something to determine based on the content below!

### What part(s) of the page would you like to see updated?

Make sure there's an explanation in one or more places how to:
- add descriptions for definitions of custom generic data tests
- add descriptions for instances of singular data tests

## Overview

There are two types of data tests:
1. [Generic](https://docs.getdbt.com/docs/build/data-tests#generic-data-tests)
1. [Singular](https://docs.getdbt.com/docs/build/data-tests#singular-data-tests)

We have two issues for adding `description` to data tests:
1. https://github.com/dbt-labs/dbt-core/issues/2578
1. https://github.com/dbt-labs/dbt-core/issues/9005#issuecomment-1834047344

A major difference between custom generic data tests and singular data tests is that the former can be re-used, but the latter can't.

So there are really three ways we could potentially add a description to data tests:
1. Definitions of generic data tests
1. Instances of generic data tests
1. Instances of singular data tests

(There's not a 4th option because there's only one instance per definition of a singular data test.)

## Details

Generic data tests have one macro _definition_ and then zero to many _instances_ where they are used. So that's two different places we can imagine adding a description for generic data tests.

However, for singular data tests, there's one instance for each definition -- they are one-to-one. So there's only one description possible for that type of data test. 

### Descriptions for reusable definitions of generic data tests

Since the _definition_ is just a macro, the definition of a custom generic data test can already have a [`description`](https://docs.getdbt.com/reference/resource-properties/description) like this:

```yaml
macros:
  - name: test_CUSTOM_GENERIC_TEST_NAME
    description: markdown_string
    arguments:
      - name: argument_name
        description: markdown_string
```

### Descriptions for instances of generic data tests

~However, I don't believe the _instances_ of generic data tests can be documented until https://github.com/dbt-labs/dbt-core/issues/2578 is implemented.~

Added in https://github.com/dbt-labs/dbt-core/pull/10850 to resolve https://github.com/dbt-labs/dbt-core/issues/2578!

```yaml
models:
  - name: my_model
    columns:
      - name: id
        tests:
          - unique:
              description: markdown_string
```

### Descriptions for singular data tests

Added in https://github.com/dbt-labs/dbt-core/pull/10792 to resolve https://github.com/dbt-labs/dbt-core/issues/9005!

```yaml
data_tests:
  - name: singular_data_test_name
    description: markdown_string
```

### Additional information

See https://github.com/dbt-labs/docs.getdbt.com/issues/5631 and https://github.com/dbt-labs/docs.getdbt.com/pull/6191/ for related issues.
