### ISSUE TITLE
[Core] Support a list of multiple `unique_key`s in snapshots

### ISSUE THREAD

**Issue by FishtownBuildBot** [fishtown-analytics/docs.getdbt.com#6343]
At a minimum, update body to include a link to the page on docs.getdbt.com requiring updates and what part(s) of the page you would like to see updated.
Originating from this issue: https://github.com/dbt-labs/dbt-core/issues/9992
Pull request: https://github.com/dbt-labs/dbt-core/pull/10795

**Comment by runleonarun** [comment]
## Documentation plan

- Update this page https://docs.getdbt.com/reference/resource-configs/unique_key
	- [x] Revise the description to account for multiple unique keys
	- [x] Add an example for using multiple unique keys: multiple `id` columns as unique key:

### Use multiple unique keys 

      ```
      snapshots:
        - name: orders_snapshot
          relation: source('jaffle_shop', 'orders')
          config:
            schema: snapshots
            unique_key: 
              - order_id
              - product_id
            strategy: timestamp
            updated_at: updated_at
      ```
- Update this page https://docs.getdbt.com/docs/build/snapshots#configuring-snapshots 
	 - [ ] Update the example in the table on this page to include an array for two unique ids [order_id, product_id]
	 - [ ] Update description in table to say can be string or array. 
- Possibly update examples in these pages to become arrays if it's recommended (in question 4)
    - https://docs.getdbt.com/docs/build/snapshots
    - https://docs.getdbt.com/reference/snapshot-properties
    - https://docs.getdbt.com/reference/commands/snapshot

Questions:

1. Does this plan seem OK / solid?
2. Does this replace concatenating columns as unique keys or is that still good practice?
3. Can we also use inline notation for these arrays For example, `unique_key [order_id, product_id]` or do we prefer block notations as shown in the example above?
4. Are multiple unique_keys backwards compatible to previous dbt versions or do I need to version these examples and content?
5. Should I change all unique_key examples on the snapshot_configs page to become arrays? IOW, is it understood that if you use an array you can also use a string?  https://docs.getdbt.com/reference/snapshot-configs
