### ISSUE TITLE
Defining `column_name` in YAML for generic data tests is only for advanced use cases

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/docs.getdbt.com#6436]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/resource-properties/data-tests#test-an-expression

### What part(s) of the page would you like to see updated?

It looks to me like the code example [here](https://docs.getdbt.com/reference/resource-properties/data-tests#test-an-expression) lead to some confusion: https://github.com/dbt-labs/dbt-core/issues/10966#issuecomment-2461097017).

I don't know off the top of my head how we could/should refactor it, but we should give it a look if we can.

Currently, this code example seems to be trying to cover two things at the same time:
- Using a SQL expression within a data test
- Apply the data test to a model instead of a column

So maybe things will be less confusing if those two things are split into their own separate code examples?

It might be helpful to use a different example for SQL expressions. One idea is [`expression_is_true`](https://github.com/dbt-labs/dbt-utils?tab=readme-ov-file#expression_is_true-source) from dbt-utils:

### Test an expression

```yaml
models:
  - name: model_name
    tests:
      - dbt_utils.expression_is_true:
          expression: "col_a + col_b = total"
```

Another example:

```yaml
models:
  - name: model_name
    tests:
      - dbt_utils.expression_is_true:
          expression: "delivery_date >= order_date"
```

Something to keep in mind is that [this](https://github.com/dbt-labs/dbt-utils?tab=readme-ov-file#unique_combination_of_columns-source) looks like it originally pointed to [this](https://docs.getdbt.com/reference/resource-properties/data-tests#test-an-expression) example:

```yaml
models:
  - name: orders
    tests:
      - unique:
          column_name: "country_code || '-' || order_id"
```
