### ISSUE TITLE
join_to_timespine is incorrectly indented in the simple metric example

### ISSUE THREAD

**Issue by joellabes** [fishtown-analytics/docs.getdbt.com#6685]
### Contributions

- [x] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

[As reported by friend of the show Amanda](https://dbt-labs.slack.com/archives/C01MAK0JJU8/p1734451749685839):

> the join_to_timespine parameter is at the same level of indentation as type_params, but I found that dbt wouldn't compile correctly until I nested join_to_timespine under the measure block

I looked into it, and the filter_to_timespine property was accidentally outdented in #5409 while fixing the indentation for filters. 

### What part(s) of the page would you like to see updated?

It should be: 

```yml
metrics:
  - name: cancellations
    description: The number of cancellations
    type: simple
    label: Cancellations
    type_params:
      measure:
        name: cancellations_usd  # Specify the measure you are creating a proxy for.
        fill_nulls_with: 0
        join_to_timespine: true
    filter: |
      {{ Dimension('order__value')}} > 100 and {{Dimension('user__acquisition')}} is not null
```
