### ISSUE TITLE
column_types is case sensitive

### ISSUE THREAD

**Issue by aspfohl** [fishtown-analytics/docs.getdbt.com#669]
### Describe the bug
dbt resource config [column_types](https://docs.getdbt.com/reference/resource-configs/column_types) is case sensitive

### Steps To Reproduce
data/my_database/my_schema/foo.csv:
```csv
EXAMPLE_COL
1
```

in dbt_project.yml:
```yaml
seeds:
    my_project:
        my_database:
            my_schema:
                foo:
                    +column_types:
                        example_col: varchar(5)
```

```bash
$ dbt seed -s foo
...
Compilation Error in seed foo (data/my_database/my_schema/foo.csv)
  "example_col" does not match the name of any column in this table.

  > in macro materialization_seed_default (macros/materializations/seed/seed.sql)
  > called by seed foo (data/my_database/my_schema/foo.csv)

Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

### Expected behavior
column_types should be case insensitive 

### Screenshots and log output
n/a

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.19.1
   latest version: 0.19.1

Up to date!

Plugins:
  - bigquery: 0.19.1
  - snowflake: 0.19.1
  - redshift: 0.19.1
  - postgres: 0.19.1
```

**The operating system you're using:** macos 

**The output of `python --version`:** Python 3.7.8

### Additional context
Also breaks the opposite way:

```csv
example_col
1
```

in dbt_project.yml:
```yaml
seeds:
    my_project:
        my_database:
            my_schema:
                foo:
                    +column_types:
                        EXAMPLE_COL: varchar(5)
```
