### ISSUE TITLE
[Core] new loaded_at_query config for source freshness - dbt-core Issue #8797

### ISSUE THREAD

**Issue by FishtownBuildBot** [fishtown-analytics/docs.getdbt.com#6695]
Originating from this issue: https://github.com/dbt-labs/dbt-core/issues/8797

Existing docs page on source freshness: https://docs.getdbt.com/reference/resource-properties/freshness

new `loaded_at_query` config for source freshness - the ability to specify **custom sql** to generate the `maxLoadedAt` time stamp on the source (vs. the "built-in" one which uses the `loaded_at_field` - [collect_freshness](https://github.com/dbt-labs/dbt-adapters/blob/6c41bedf27063eda64375845db6ce5f7535ef6aa/dbt/include/global_project/macros/adapters/freshness.sql#L4-L16))

example (check this works):
```
sources:
  - name: my_source
    freshness:
      error_after:
        count: 2
        period: hour 
    loaded_at_query: |
      select from audit_tables
      where table_name = {{ this.identifier }}
      and status = 'completed'
```

Notes:
- **cannot** specify _both_ `loaded_at_field` and `loaded_at_query`:
```
sources:
  - name: jaffle_shop
    database: raw
    freshness: 
      error_after: {count: 24, period: hour}
    loaded_at_field: _etl_loaded_at
    loaded_at_query: ...
```
- if you specify something like this, whatever is "closest" to the table wins:
```
sources:
  - name: jaffle_shop
    database: raw
    freshness: 
      error_after: {count: 24, period: hour}
    loaded_at_field: _etl_loaded_at
    tables:
      - name: orders
        loaded_at_query: ...
```
- [filter](https://docs.getdbt.com/reference/resource-properties/freshness#filter) won't work for `loaded_at_query`
