### ISSUE TITLE
[Core] Docs Changes  for new state orchestration model config

### ISSUE THREAD

**Issue by FishtownBuildBot** [fishtown-analytics/docs.getdbt.com#6730]
Document new  configuration on the model to support adaptive job

```
models:
  - name: stg_orders
    freshness:
      # build this model after X amount of time, as long as it has new data
      build_after: 
        count: 4
        period: hour
        depends_on: all
```
## Acceptance criteria
The new configuration will be parsed and represented on the model node after the parsing phase.

 Originating from this issue: https://github.com/dbt-labs/dbt-core/issues/11123

## reference
[internal related convo](https://dbt-labs.slack.com/archives/C073SHADXGB/p1732307685615149)
[docs project](https://www.notion.so/dbtlabs/Beta-Core-1-10-185bb38ebda780a7a11ce5c32d1ab533?pvs=4)
