### ISSUE TITLE
all snapshot_meta_column_names including dbt_is_deleted should be a string input not a boolean

### ISSUE THREAD

**Issue by graciegoheen** [fishtown-analytics/docs.getdbt.com#6747]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/resource-configs/snapshot_meta_column_names

### What part(s) of the page would you like to see updated?

Right now it says to input a boolean for `snapshot_meta_column_names` `dbt_is_deleted`:
```
snapshots:
  - name: <snapshot_name>
    config:
      snapshot_meta_column_names:
        dbt_valid_from: <string>
        dbt_valid_to: <string>
        dbt_scd_id: <string>
        dbt_updated_at: <string>
        dbt_is_deleted: <boolean>
```
Instead it should be a string:
```
snapshots:
  - name: <snapshot_name>
    config:
      snapshot_meta_column_names:
        dbt_valid_from: <string>
        dbt_valid_to: <string>
        dbt_scd_id: <string>
        dbt_updated_at: <string>
        dbt_is_deleted: <string>
```
