### ISSUE TITLE
[Bug] adapter deleted most of my bucket.

### ISSUE THREAD

**Issue by nbenezri** [fishtown-analytics/docs.getdbt.com#7231]
### Is this a new bug in dbt-athena?

- [X] I believe this is a new bug in dbt-athena
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I am doing a POC with athena where I try to load data from parquet file into iceberg.
The parquet table was created outsides of dbt with create external table syntax on bucket-a.
In dbt configuration I mention iceberg destination as bucket-b and I don't specify anywhere bucket-a.
I notice after a few test run (first time using this) - that most of bucket -a was deleted. tracing it back with aws cloud train and datadog I found it was dbt-athena that deleted those files with deleteobejcts API call.
Since it was during the initial creation of the repo/poc, I am not sure which configuration exactly was it that led to it. nor do I want to test again as I am not sure how it happen. Luckily the bucket had versioning. Any idea what in this adapter may cause this?

### Expected Behavior

dbt does not touch buckets outsides of the models-scope 

### Steps To Reproduce

I dont have a way to reproduce.

What I can say that the model was:
**models/project/staging/stg_raw_tab.sql:**
```
{{ config(
    materialized='table',
    table_type='iceberg',
    format='parquet'
) }}
WITH
tab AS (
SELECT id, name 
FROM db_dev.parquet_tab
LIMIT 1
)

SELECT *
FROM tab
```

and table ddl is:

```
CREATE external TABLE db_dev.parquet_tab(
id bigint,
name varchar(100)
)
PARTITIONED BY ( 
  `date` string
)
ROW FORMAT SERDE "org.apache.hive.hcatalog.data.JsonSerDe"
WITH SERDEPROPERTIES (
    'ignore.malformed.json' = 'true'
)
LOCATION 's3://<bucket-a>/<path>/'
TBLPROPERTIES (
    'projection.enabled' = 'true',
    'json.max.read.errors' = '100',
    'compression.type' = 'GZIP' ,
    'projection.enabled' = 'true',
  'projection.date.type' = 'date',
  'projection.date.interval' = '1',
  'projection.date.format' = 'yyyy/MM/dd',
  'timestamp.formats' = "yyyyMMdd'T'HH:mm:ss",
  'projection.date.unit' = 'DAYS',
  'projection.date.range' = '2021/01/01,NOW',
  'storage.location.template' = 's3://<bucket-a>/<path>/${date}/'
);
```

latest profile

```
iceberg_dbt:
  target: athena_dev
  outputs:
    athena_dev:
      type: athena
      s3_staging_dir: s3://<bucket-c>/dbt/
      s3_data_dir: s3://<bucket-b>/
      s3_data_naming: table_unique
      s3_tmp_table_dir: s3://<bucket-b>/temp/
      region_name: us-east-1
      schema: db_dev
      database: awsdatacatalog
      threads: 4
      aws_profile_name: default
      work_group: iceberg
```

### Environment

```markdown
nir % python3 --version
Python 3.12.8
nir % dbt --version
Core:
  - installed: 1.9.1
  - latest:    1.9.1 - Up to date!

Plugins:
  - glue:     1.9.0 - Up to date!
  - redshift: 1.9.0 - Up to date!
  - postgres: 1.9.0 - Up to date!
  - spark:    1.9.0 - Up to date!
  - athena:   1.8.4 - Update available!

  At least one plugin is out of date with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation


nir % sw_vers
ProductName:            macOS
ProductVersion:         15.1.1
BuildVersion:           24B91
```
```


### Additional Context

_No response_
