### ISSUE TITLE
[Core] Freshness is now a config (not a property) - dbt-core Issue #11506

### ISSUE THREAD

**Issue by FishtownBuildBot** [fishtown-analytics/docs.getdbt.com#7334]
### New deprecation warning `PropertyMovedToConfigDeprecation`

This is for things that were historically properties, that are fully moving to configs.

This will include: `freshness`, `meta`, `tags`, `docs`, `group`, and `access`

The benefit of moving these to be `config`s is you can set them for many resources at once in `dbt_project.yml` (project-level/folder-level defaults). More info on the difference between properties and configs [here](https://docs.getdbt.com/reference/configs-and-properties).

#### Example:

If you previously had source freshness defined as a property:
```
sources: 
  - name: ecom
    schema: raw
    description: E-commerce data for the Jaffle Shop
    freshness:
      warn_after:
        count: 24
        period: hour
```

You should move it under `config`:
```
sources: 
  - name: ecom
    schema: raw
    description: E-commerce data for the Jaffle Shop
    config:
      freshness:
        warn_after:
          count: 24
          period: hour
```

### Docs pages to be updated

top priority:
- [deprecations](https://docs.getdbt.com/reference/deprecations) page
- 1.10 guide ([deprecation warnings section](https://docs.getdbt.com/docs/dbt-versions/core-upgrade/upgrading-to-v1.10#deprecation-warnings))

second priority:
- any examples in our docs of `freshness`, `meta`, `tags`, `docs`, `group`, and `access` should be nested under `config`

### Originating from this issue: https://github.com/dbt-labs/dbt-core/issues/11506
