### ISSUE TITLE
docs for spec of new `catalogs` coming in 1.10

### ISSUE THREAD

**Issue by graciegoheen** [fishtown-analytics/docs.getdbt.com#7367]
### Contributions

- [x] I have read the contribution docs, and understand what's expected of me.

### What part(s) of the page would you like to see updated?

We need technical docs here describing the actual spec of `catalogs` coming in dbt core `1.10`:
- what the properties are
- what they mean
- etc.

examples (to be checked) of configuring the top-level catalogs key:

```
catalogs:
  - name: catalog_dave
    # materializing the data to an external location, and metadata to that data catalog
    write_integrations: 
      - name: databricks_glue_write_integration
          external_volume: databricks_external_volume_prod
          table_format: iceberg
          catalog_type: unity 
```

and adding it to a model:
```
# models/schema.yml
models:
  - name: my_second_public_model
    config:
      catalog_name: catalog_dave
```

We should also document the existing `catalog` databricks-specific alias for `database` - see [slack thread](https://dbt-labs.slack.com/archives/C08PAK7CH7V/p1748633641478279?thread_ts=1748628232.750229&cid=C08PAK7CH7V):
- https://docs.getdbt.com/reference/resource-configs/databricks-configs
- https://docs.getdbt.com/reference/resource-configs/database#warehouse-specific-information

### Additional information

From PRs:
- https://github.com/dbt-labs/dbt-core/pull/11162
- https://github.com/dbt-labs/dbt-adapters/pull/1134

[internal notion](https://www.notion.so/dbtlabs/RFC-94-Cross-Platform-Mesh-142bb38ebda780b4befdee9b7e09902b?pvs=4#143bb38ebda7809489a3f221560db3e6) with initial properties defined 

Feel free to reach out to me or @colin-rogers-dbt for help with technical content!
