### ISSUE TITLE
Understanding the use of --selector and --models together

### ISSUE THREAD

**Issue by rahul-ve** [fishtown-analytics/docs.getdbt.com#803]
Hi team,

I am referring to the doc about node selection, https://docs.getdbt.com/reference/node-selection/syntax
Based on my testing locally, looks like if both `--models` and `--selector` options are passed in, `--models` options is being ignored  This is not clearly documented  hence asking. Is this the expected behavior?

We have a situation where we have a selector defined to exclude a bunch of models but we wanted to select a particular model from the excluded list to also be run at times. This can be achieved by modifying the selector using union, exclude logic but we only want the excluded model to run based on some logic during CI run. 

Thanks!

**Comment by danieldiamond** [comment]
@jtcohen6 on your suggestion above using anchors, do you know how to _dynamically_ set the `standard-selection` alias?

context: we have two default selector definitions (depending on which environment) i.e. each selector definition has have the default rule
```yaml
default: "{{ target.type == 'snowflake' | as_bool }}"
```

so there are two `standard-definition` selectors. and for `my_ci_logic`, i would it to defer to the right selector. the problem is I cant see a way to set the alias i.e. this doesn't work:
```yaml
...
  - name: my_ci_logic
    description: "For use in CI"
    definition:
      union:
        - "*{{ target.type }}"
```

i'm also unable to set variables at the top level
```yaml
variables:
  - name: dynamic_default_selection_name
    value: "{{ target.type }}"
...
  - name: my_ci_logic
    description: "For use in CI"
    definition:
      union:
        - *$(dynamic_default_selection_name)
```
